development:
  adapter: postgresql
  encoding: unicode
  database: nsa_snowden_development
  pool: 5
  username: michaelreinhart
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: nsa_snowden_test
  pool: 5
  username: michaelreinhart
  password:
  host: localhost